Refactor the asset crate
Manta-Network/pallet-manta-asset pull request #1
Opened 2021-05-17 13:00 UTC by zhenfeizhang

2021-05-17 18:45 UTC, ghzlatarev commented on Cargo.toml
Looks like an extra space.

2021-05-17 18:46 UTC, ghzlatarev commented on Cargo.toml
> +manta-crypto = { branch = "refactoring-pallet-manta-pay's-crypto-code", git = "https://github.com/Manta-Network/manta-crypto/", default = false }
Are you sure you want to leave this branch here ?

2021-05-17 18:58 UTC, zhenfeizhang commented on Cargo.toml
> +manta-crypto = { branch = "refactoring-pallet-manta-pay's-crypto-code", git = "https://github.com/Manta-Network/manta-crypto/", default = false }
yeah... otherwise the CI will fail... we need to merge https://github.com/Manta-Network/manta-crypto/pull/1 first.

2021-05-17 18:59 UTC, zhenfeizhang commented on Cargo.toml
thanks. Fixed.

2021-05-17 20:31 UTC, stechu commented on src/serdes.rs
> +	fn deserialize<R: Read>(mut reader: R) -> Self {
a design question here. Do you think it will be helpful to add a checksum when serialize/deserialize? So when the user read a UTXO, they can make sure it is not corrupted?

2021-05-18 00:23 UTC, stechu commented
Please add a readme for the repo.

2021-05-18 00:26 UTC, stechu requested changes
LGTM in general. Please add a readme file for the repo. Also, any comment for the checksum suggestion?

2021-05-18 00:45 UTC, zhenfeizhang commented on src/serdes.rs
> +	fn deserialize<R: Read>(mut reader: R) -> Self {
not sure... perhaps on the local disc but not on ledger?

2021-05-18 00:58 UTC, zhenfeizhang commented
> LGTM in general. Please add a readme file for the repo. Also, any comment for the checksum suggestion?

done. @stechu

2021-05-18 02:36 UTC, zhenfeizhang commented on src/serdes.rs
> +	fn deserialize<R: Read>(mut reader: R) -> Self {
done...

2021-05-18 02:55 UTC, zhenfeizhang commented
@ghzlatarev linter failed :-( can you please help to fix?

2021-05-18 08:15 UTC, ghzlatarev commented
> @ghzlatarev linter failed :-( can you please help to fix?

On it.

2021-05-18 08:41 UTC, ghzlatarev commented
Guys don't forget to add some branch protection rules. Currently I can merge the request.

2021-05-18 14:05 UTC, zhenfeizhang commented
> > @ghzlatarev linter failed :-( can you please help to fix?
> 
> On it.
> 
> EDIT: Ok linter passed now. Logged this issue #2 . Should save us some time in reviews.

Thanks!

2021-05-18 14:06 UTC, zhenfeizhang commented
> Guys don't forget to add some branch protection rules. Currently I can merge the request.

@stechu 

Also please set up for other repos too.

2021-05-18 16:31 UTC, ghzlatarev commented on src/lib.rs
> +/// are needed for the receiver to spend a coin from a receiver
This line is not clear " for receiver from receiver "

2021-05-18 16:32 UTC, ghzlatarev commented on src/lib.rs
> +/// see paper for the above definitions
What paper do you mean? I searched in our white paper pdf for "rho" and couldn't find anything.

2021-05-18 16:33 UTC, ghzlatarev commented on src/lib.rs
> +/// - some public information s
Something like this for "r" and "dh_pk" would be nice.

2021-05-18 20:56 UTC, zhenfeizhang commented on src/lib.rs
> +/// - some public information s
done.

2021-05-18 20:57 UTC, zhenfeizhang commented on src/lib.rs
> +/// see paper for the above definitions
the white paper. You need to look for the greek letter `rho` which sounds like `ro:` and looks like `p`.

2021-05-18 20:58 UTC, zhenfeizhang commented on src/lib.rs
> +/// are needed for the receiver to spend a coin from a receiver
thank! fixed.

2021-05-19 09:06 UTC, ghzlatarev commented on .github/workflows/check.yml
> +          cargo +nightly fmt --all -- --check
Should we also run the tests with +nightly flag ?

2021-05-19 11:18 UTC, zhenfeizhang commented on .github/workflows/check.yml
> +          cargo +nightly fmt --all -- --check
I just realized that we have been using nightly for CI all the time...
https://github.com/Manta-Network/pallet-manta-asset/blob/28f4cdf455e76cce766bbd66c00bfb5895b53c7c/.github/workflows/check.yml#L45
lol.          
And perhaps also for other CIs...

I think we should compile for both stable and nightly.
For testing, with stable should be sufficient.
I believe that we will only release with stable rust, and some of our test is too long to run twice...

2021-05-19 11:28 UTC, ghzlatarev commented on .github/workflows/check.yml
> +          cargo +nightly fmt --all -- --check
Ok let's remove the ``` rustup default nightly``` and start using the flag only when we need to.
I'll change it in the Manta and pallet-manta-pay repos in my next PRs.

2021-05-19 11:29 UTC, zhenfeizhang commented on .github/workflows/check.yml
> +          cargo +nightly fmt --all -- --check
cool. Thanks!

2021-05-19 11:57 UTC, ghzlatarev commented
> _No description provided._

No commit message.

2021-05-19 12:04 UTC, ghzlatarev approved these changes

2021-05-19 12:23 UTC, zhenfeizhang commented on README.md
> +assets from others generates. It contains necessary address related information,
done

2021-05-19 16:10 UTC, stechu approved these changes

2021-05-19 16:23 UTC, merged